=== certxg/db2xml/dbsql2xml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xmlNamespace1998.xsd"/>
  <xs:element name="config">
    <xs:complexType mixed="false">
      <xs:all>
        <xs:element minOccurs="1" maxOccurs="1" ref="tokenForCommandLineStringArrays"/>
        <xs:element minOccurs="1" maxOccurs="1" ref="globalCharsetName"/>
        <xs:element minOccurs="1" maxOccurs="1" ref="connectionProperties"/>
        <xs:element minOccurs="1" maxOccurs="1" ref="globalVariables"/>
        <xs:element minOccurs="1" maxOccurs="1" ref="processingInstructions"/>
        <xs:element minOccurs="1" maxOccurs="1" ref="table"/>
      </xs:all>
    </xs:complexType>
    <xs:unique name="globalVariableHasToBeUnique">
      <xs:selector xpath=".//column"/>
      <xs:field xpath="@globalVariableName"/>
    </xs:unique>
  </xs:element>
  <xs:element name="tokenForCommandLineStringArrays" type="xs:string"/>
  <xs:element name="globalCharsetName" type="xs:string"/>
  <xs:element name="connectionProperties">
    <xs:complexType>
      <xs:all>
        <xs:element minOccurs="1" maxOccurs="1" ref="jdbcDriver"/>
        <xs:element minOccurs="1" maxOccurs="1" ref="jdbcURL"/>
        <xs:element minOccurs="1" maxOccurs="1" ref="jdbcUserName"/>
        <xs:element minOccurs="1" maxOccurs="1" ref="jdbcPassword"/>
        <xs:element minOccurs="1" maxOccurs="1" ref="multiStatementDriver"/>
      </xs:all>
    </xs:complexType>
  </xs:element>
  <xs:element name="jdbcDriver" type="xs:string"/>
  <xs:element name="jdbcURL" type="xs:anyURI"/>
  <xs:element name="jdbcUserName" type="xs:string"/>
  <xs:element name="jdbcPassword" type="xs:string"/>
  <xs:element name="multiStatementDriver" type="xs:boolean"/>
  <xs:element name="globalVariables">
    <xs:complexType mixed="false">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="globalVariable"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="globalVariable">
    <xs:complexType mixed="true">
      <xs:attribute name="name" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="processingInstructions">
    <xs:complexType mixed="false">
      <xs:choice>
        <xs:element minOccurs="0" maxOccurs="1" ref="css"/>
        <xs:element minOccurs="0" maxOccurs="1" ref="xslt"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="css" type="xs:anyURI"/>
  <xs:element name="xslt" type="xs:anyURI"/>
  <xs:element name="table">
    <xs:complexType mixed="false">
      <xs:sequence>
        <xs:element minOccurs="1" maxOccurs="unbounded" ref="column"/>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="table"/>
      </xs:sequence>
      <xs:attribute name="xmlName" use="required" type="xs:NCName"/>
      <xs:attribute name="sql" use="required"/>
      <xs:attribute ref="xml:base" use="optional"/>
      <xs:attribute ref="xml:lang" use="optional"/>
      <!--<xs:attribute name="id" type="xs:ID" use="optional"/>-->
    </xs:complexType>
  </xs:element>
  <xs:element name="column">
    <xs:complexType mixed="false">
      <xs:attribute name="xmlName" use="required" type="xs:NCName"/>
      <xs:attribute name="sqlName" use="required" type="xs:NCName"/>
      <xs:attribute name="globalVariableName" use="optional"/>
      <xs:attribute name="charsetName" use="optional"/>
      <xs:attribute ref="xml:base" use="optional"/>
      <xs:attribute ref="xml:lang" use="optional"/>
      <!--<xs:attribute name="id" type="xs:ID" use="optional"/>-->
    </xs:complexType>
  </xs:element>
</xs:schema>

=== certxg/db2xml/productMappingToBeXIncludedIntoTreeXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dbsql2xml.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">
  <tokenForCommandLineStringArrays>#</tokenForCommandLineStringArrays>
  <globalCharsetName>UTF-8</globalCharsetName>
  <connectionProperties>
    <jdbcDriver>com.mysql.jdbc.Driver</jdbcDriver> 
    <jdbcURL>jdbc:mysql://localhost:3306/sales</jdbcURL>
    <jdbcUserName>root</jdbcUserName>
    <jdbcPassword>admin</jdbcPassword>
    <multiStatementDriver>false</multiStatementDriver>
  </connectionProperties>
  <globalVariables>
    <globalVariable name="$item.productId">-1</globalVariable>
  </globalVariables>
  <processingInstructions>
    <!--<css>css/dbsql2xml.css</css>-->
    <!--<xslt>xslt/dbsql2xml.xsl</xslt>-->
  </processingInstructions>
  <table xmlName="product" sql="SELECT * FROM product WHERE product_id = $item.productId">
    <column xmlName="id" sqlName="product_id"/>
    <column xmlName="name" sqlName="name" charsetName="ISO-8859-2"/>
    <column xmlName="price" sqlName="price"/>
  </table>
</config>

=== certxg/db2xml/flatXMLMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dbsql2xml.xsd">
  <tokenForCommandLineStringArrays>#</tokenForCommandLineStringArrays>
  <globalCharsetName>UTF-8</globalCharsetName>

  <connectionProperties>
    <!-- <jdbcDriver>org.hsqldb.jdbcDriver</jdbcDriver> -->
    <!-- <jdbcURL>jdbc:hsqldb:hsql://localhost/</jdbcURL>  -->

    <jdbcDriver>com.mysql.jdbc.Driver</jdbcDriver> 
    <jdbcURL>jdbc:mysql://localhost:3306/sales</jdbcURL>
    <jdbcUserName>root</jdbcUserName>
    <jdbcPassword>admin</jdbcPassword>
    <multiStatementDriver>false</multiStatementDriver>

  </connectionProperties>

  <globalVariables>
    <globalVariable name="$gv00">10</globalVariable>
  </globalVariables>
  <processingInstructions>
    <!--<css>css/dbsql2xml.css</css>-->
    <!--<xslt>xslt/dbsql2xml.xsl</xslt>-->
  </processingInstructions>
  <table xmlName="invoice" sql="select invoice.invoice_id as &quot;invoice.invoice_id&quot;, invoice.customer_id as &quot;invoice.customer_id&quot;, invoice.total as &quot;invoice.total&quot;, item.invoice_id as &quot;item.invoice_id&quot;, item.item_id as &quot;item.item_id&quot;, item.product_id as &quot;item.product_id&quot;, item.quantity as &quot;item.quantity&quot;, item.cost as &quot;item.cost&quot;, product.product_id as &quot;product.product_id&quot;, product.name as &quot;product.name&quot;, product.price as &quot;product.price&quot;, customer.customer_id as &quot;customer.customer_id&quot;, customer.first_name as &quot;customer.first_name&quot;, customer.last_name as &quot;customer.last_name&quot;, customer.street as &quot;customer.street&quot;, customer.city as &quot;customer.city&quot; from invoice, item, product, customer where invoice.invoice_id=item.invoice_id and item.product_id=product.product_id and invoice.customer_id=customer.customer_id and invoice.invoice_id = $gv00">
    <column xmlName="invoice.id" sqlName="invoice.invoice_id"/>
    <column xmlName="invoice.customerid" sqlName="invoice.customer_id"/>
    <column xmlName="invoice.total" sqlName="invoice.customer_id"/>
    <column xmlName="item.invoiceid" sqlName="item.invoice_id"/>
    <column xmlName="item.item" sqlName="item.item_id"/>
    <column xmlName="item.productid" sqlName="item.product_id"/>
    <column xmlName="item.quantity" sqlName="item.quantity"/>
    <column xmlName="item.cost" sqlName="item.cost"/>
    <column xmlName="product.id" sqlName="product.product_id"/>
    <column xmlName="product.name" sqlName="product.name"/>
    <column xmlName="product.price" sqlName="product.price"/>
    <column xmlName="customer.id" sqlName="customer.customer_id"/>
    <column xmlName="customer.firstname" sqlName="customer.first_name"/>
    <column xmlName="customer.lastname" sqlName="customer.last_name"/>
    <column xmlName="customer.street" sqlName="customer.street"/>
    <column xmlName="customer.city" sqlName="customer.city"/>
  </table>
</config>

=== certxg/db2xml/treeXMLMapping.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dbsql2xml.xsd">
  <tokenForCommandLineStringArrays>#</tokenForCommandLineStringArrays>
  <globalCharsetName>UTF-8</globalCharsetName>
  <connectionProperties>
    <jdbcDriver>com.mysql.jdbc.Driver</jdbcDriver> 
    <jdbcURL>jdbc:mysql://localhost:3306/sales</jdbcURL>
    <jdbcUserName>root</jdbcUserName>
    <jdbcPassword>admin</jdbcPassword>
    <multiStatementDriver>false</multiStatementDriver>
  </connectionProperties>
  <globalVariables>
    <globalVariable name="$gv00">10</globalVariable>
  </globalVariables>
  <processingInstructions>
    <!--<css>css/dbsql2xml.css</css>-->
    <!--<xslt>xslt/dbsql2xml.xsl</xslt>-->
  </processingInstructions>
  <table xmlName="invoice" sql="SELECT * FROM invoice WHERE invoice_id = $gv00">
    <column xmlName="id" sqlName="invoice_id" globalVariableName="$gv01"/>
    <column xmlName="customer_Id" sqlName="customer_id" globalVariableName="$gv02"/>
    <column xmlName="total" sqlName="TOTAL"/>
    <table xmlName="customer" sql="SELECT * FROM customer WHERE customer_id = $gv02">
      <column xmlName="id" sqlName="customer_id"/>
      <column xmlName="firstName" sqlName="first_name"/>
      <column xmlName="lastName" sqlName="last_name"/>
      <column xmlName="street" sqlName="street"/>
      <column xmlName="city" sqlName="city"/>
    </table>
    <table xmlName="item" sql="SELECT * FROM item WHERE invoice_id = $gv01">
      <column xmlName="invoiceId" sqlName="invoice_id"/>
      <column xmlName="item" sqlName="item_id"/>
      <column xmlName="productId" sqlName="product_id" globalVariableName="$gv03"/>
      <column xmlName="quantity" sqlName="quantity"/>
      <column xmlName="cost" sqlName="cost"/>
      <table xmlName="product" sql="SELECT * FROM product WHERE product_id = $gv03">
        <column xmlName="id" sqlName="product_id"/>
        <column xmlName="name" sqlName="name"/>
        <column xmlName="price" sqlName="price"/>
      </table>
    </table>
  </table>
</config>

=== certxg/db2xml/treeXMLMappingWithXInclusionAndCharset.xml
<?xml version="1.0" encoding="UTF-8"?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="dbsql2xml.xsd" xmlns:xi="http://www.w3.org/2001/XInclude">
  <tokenForCommandLineStringArrays>#</tokenForCommandLineStringArrays>
  <!-- names and values of global variables Strings are delimited by this character; change it, if You need -->
  <globalCharsetName>UTF-8</globalCharsetName>
  <connectionProperties>
    <jdbcDriver>com.mysql.jdbc.Driver</jdbcDriver> 
    <jdbcURL>jdbc:mysql://localhost:3306/sales</jdbcURL>
    <jdbcUserName>root</jdbcUserName>
    <jdbcPassword>admin</jdbcPassword>

    <!-- here is blank password -->
    <multiStatementDriver>false</multiStatementDriver>
    <!-- this means, that HSQLDB JDBC driver can have multiple ResultSet-s per one Connection, which is significantly faster then one-per-one; if You are not sure, set "true" -->
  </connectionProperties>
  <globalVariables>
    <globalVariable name="$gv00">10</globalVariable>
    <!-- these global variables (in mapping XML) are covered by these ones cet by constructor; so $gv00=10 from <globalVariable> together $gv00=20 from constructor will result in $gv00=20 -->
  </globalVariables>
  <processingInstructions>
    <!--<css>css/dbsql2xml.css</css>-->
    <!--<xslt>xslt/dbsql2xml.xsl</xslt>-->
  </processingInstructions>
  <table xmlName="invoice" sql="SELECT * FROM invoice WHERE invoice_id = $gv00">
    <!-- "$gv00" will be replaced by its value -->
    <column xmlName="id" sqlName="invoice_id" globalVariableName="$invoice.id"/>
    <!-- remember value of column "id" for use in SQL select in "item" table -->
    <column xmlName="customerId" sqlName="customer_id" globalVariableName="$invoice.customerId"/>
    <!-- remember value of column "customerId" for use in SQL select in "customer" table -->
    <column xmlName="total" sqlName="TOTAL"/>
    <table xmlName="customer" sql="SELECT * FROM customer WHERE customer_id = $invoice.customerId">
      <column xmlName="id" sqlName="customer_id"/>
      <column xmlName="firstName" sqlName="first_name" charsetName="UTF-8"/>
      <!-- column "firstname" is (String) in "UTF-8" character encoding -->
      <column xmlName="lastName" sqlName="last_name" charsetName="windows-1250"/>
      <!-- column "lastname" is (String) in "windows-1250" character encoding -->
      <column xmlName="street" sqlName="street"/>
      <column xmlName="city" sqlName="city"/>
    </table>
    <table xmlName="item" sql="SELECT * FROM item WHERE invoice_id = $invoice.id">
      <column xmlName="invoiceId" sqlName="invoice_id"/>
      <column xmlName="item" sqlName="item_id"/>
      <column xmlName="productId" sqlName="product_id" globalVariableName="$item.productId"/>
      <!-- remember value of column "productId" for use in SQL select in "product" table -->
      <column xmlName="quantity" sqlName="quantity"/>
      <column xmlName="cost" sqlName="cost"/>
      <xi:include href="productMappingToBeXIncludedIntoTreeXML.xml" xpointer="element(/1/6)"/>
      <!-- use XInclusion to include (reuse) mapping of "product" table; results of "treeXMLMappingWithXInclusionAndCharset.xml" and "treeXMLOut.xml" should be the same -->
      <!-- AFAIK Java2 1.5.0_xx (its JAXP) support only first level XInclude, so XInclusion so only "B.xml" -> "A.xml" will work, not "C.xml" -> "B.xml" -> "A.xml" -->
    </table>
  </table>
</config>
